---

- hosts: all
  become: true
  tasks:
  
  - name: install updates (RedHat)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 & php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd & php package
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"
