---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (RedHat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 & php package
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd & php package
    tags: apache,apache2,RedHat
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"



- hosts: db_servers
  become: true
  tasks:
    
    - name: install mariadb package(RedHat)
      tags: db,mariadb,RedHat
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "RedHat"

    - name: install mariadb package (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
        
