---

- hosts: all
  become: true
  pre_tasks:
  
  - name: update repo cache (RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: fasle
    when: ansible_distribution == "RedHat"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
        
    - name: add ssh key for user yaay
      tags: always
      authorized_key:
        user: yaay
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHeTITklu0rKLiAmDRF+5ZKs2Ed1vhqnu2J9RHgGRQ4c ansible"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name:  install Terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 & php package
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd & php package
    tags: apache,apache2,RedHat
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: start and enable httpd (RedHat)
    tags: httpd,RedHat,apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"
  
  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd
 
  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed 
 

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
    
    - name: install mariadb package(RedHat)
      tags: db,mariadb,RedHat
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "RedHat"

    - name: install mariadb package (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
        
